### ISSUE TITLE
Per-Header / EOM Output in a verbosity level

### ISSUE THREAD

**Issue by A-c0rN** [cbs228/sameold#3]
Hey there!

I am currently writing a Python app that uses a system call to pipe external audio into an app such as this one, however I have a dilemma.
Currently, I am using Multimon-NG to do this task right now, but due to some samplerate issues, I am required to move to a new codebase for the monitoring, and SameDec is perfect, except one issue. 
With Multimon-NG, The SAME in Verbose mode allows to see "Part" Messages, or each individual data burst as they come in, as well as the End Of Messages. My codebase can work with the single Message that SameDec/SameOld puts out, however the End Of Message tones are the issue.
Due to SameOld only outputting EOMs when 3 have been received, this can cause some issues where not all 3 have been sent, received, or in some specific cases such as the Trilithic EASyPLUS and Cox Communication EAS relays, the EOMs can be faster or slower.  (Example: [Cox Communications](https://www.youtube.com/watch?v=3UhAWgwytUA), [Trilithic EASyPLUS](https://www.youtube.com/watch?v=N_VToXc7Euo))
Is it possible to make SameOld/SameDec do this in a Verbosity Level, Such as display the bursts as received and decoded?

**Comment by cbs228** [comment]
In my experience, if you are not receiving all three AFSK bursts, you are likely tuned to a station that is broadcasting a message for human consumption and not for *relay* to other stations in the EAS. These stations might not transmit EAS messages reliably, and they might not transmit the digital portion of it that samedec needs. I would avoid monitoring these stations if possible. Instead, I would recommend monitoring either NOAA All Hazards (if weather is your primary concern) or a station listed as a Local Primary in your state's EAS Plan. ([Example](https://arkbroadcasters.org/wp-content/uploads/2021/09/Arkansas-EAS-Plan.pdf) for Arkansas, see pp. 22.)

The timing interval between the AFSK bursts is standardized to 1 second ± 5% \[[source, pp. 5](https://www.nws.noaa.gov/directives/sym/pd01017012curr.pdf)\]. samedec should permit up to 1.5 seconds between bursts, which ought to be adequate. Is samedec missing bursts which are slightly too far apart?

For the specific case of not receiving the entire EOM: samedec knows the maximum length of an EAS message and will automatically issue an `NNNN` EOM after that many samples has elapsed, regardless of whether or not it receives an EOM. This will at least prevent the scenario where samedec runs "forever" while it looks in vain for an EOM.

That being said…

The 2-of-3 parity decoding makes life very difficult, and it doesn't actually improve performance at all. I've never seen the error-correction logic actually correct any errors on a production message. There is an argument to be made for optionally bypassing some of it.

We could add a fallback mode that will accept "partial" messages where we only receive two of the AFSK bursts. In the fallback mode, we perform error detection instead of error correction. Both decodes will need to be bitwise identical in order to be emitted. The fallback mode would be optional and enabled at runtime. Would this work for your application?

**Comment by A-c0rN** [comment]
> In my experience, if you are not receiving all three AFSK bursts, you are likely tuned to a station that is broadcasting a message for human consumption and not for _relay_ to other stations in the EAS.
The issue isn't that I am looking for the full message, only a way to track that I have received EOMs, Error checking or not. 
For example, if you pass live audio into Multimon-NG, it'll output an EOM per EOM you send it. That's all I need, so I can see if I have received an EOM in real-time. I do error checking on my code's end.

I have since fixed my issue, however I think per-header/EOM regardless of error checking (Like a RAW Decoder Out) feature would be well-welcomed, and would definitely make this app the best replacement for Multimon-NG, and one I would be willing to switch to.

**Comment by cbs228** [comment]
Okay, if I understand you correctly, you're looking for a faster EOM detection, right? Perhaps so you can switch off recording/playback sooner?

I think that's a bit easier than trying to output every "raw" burst. If I output raw bursts for `ZCZC` headers,

* The client has to perform error correction and determine which byte is the "last byte" of digital data. If I limit the output to only printable characters, the (nearly useless) parity-correction algorithm won't work right.

* The client has to cope with not knowing time. samedec uses a sample counter to mark time, and it knows to purge old bursts when enough time has elapsed. The client only knows wall time—not sample time—and that makes it harder to make these decisions.

This makes outputting a raw burst for `ZCZC`s unattractive.

EOM headers are different since they carry no other data. I can add a mode which will output an end-of-message as soon as it receives one of them. In this mode, there will be potentially four `NNNN` lines output: one for each burst successfully decoded *and* another one when the final decode finishes.

Fallback decoding for two-of-three bursts is a separate issue and will be tracked in #4.

**Comment by A-c0rN** [comment]
> EOM headers are different since they carry no other data. I can add a mode which will output an end-of-message as soon as it receives one of them. In this mode, there will be potentially four `NNNN` lines output: one for each burst successfully decoded _and_ another one when the final decode finishes.

This is the only thing I need. The per-header output is not necessary, and having SameOld do the error checking is fine, All I needed is the EOM detection. The 4 EOMs isn't an issue as well, I can process those out in code.
